server:
  port: 8100

spring:
  application:
    name: toy-msa-api-01
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.devyoon.kr/realms/jungryrealm
          jwk-set-uri: https://keycloak.devyoon.kr/realms/jungryrealm/protocol/openid-connect/certs

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd}}){faint} %clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){magenta} - %clr(${LOG_LEVEL_PATTERN:%-5p}) %clr(---){faint} %clr([ %-4.15t ]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"